from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(525, 377)
        MainWindow.setMinimumSize(QtCore.QSize(525, 377))
        MainWindow.setMaximumSize(QtCore.QSize(525, 377))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.manPlot = QtWidgets.QPushButton(self.groupBox)
        self.manPlot.setMinimumSize(QtCore.QSize(300, 60))
        self.manPlot.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.manPlot.setFont(font)
        self.manPlot.setObjectName("manPlot")
        self.gridLayout_2.addWidget(self.manPlot, 1, 3, 1, 1)
        self.pb_grafik_cizimi = QtWidgets.QProgressBar(self.groupBox)
        self.pb_grafik_cizimi.setProperty("value", 24)
        self.pb_grafik_cizimi.setTextVisible(False)
        self.pb_grafik_cizimi.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pb_grafik_cizimi.setObjectName("pb_grafik_cizimi")
        self.gridLayout_2.addWidget(self.pb_grafik_cizimi, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(421, 120))
        self.groupBox_2.setMaximumSize(QtCore.QSize(421, 120))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.EsikDegeri = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.EsikDegeri.setMinimumSize(QtCore.QSize(100, 30))
        self.EsikDegeri.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.EsikDegeri.setFont(font)
        self.EsikDegeri.setObjectName("EsikDegeri")
        self.gridLayout.addWidget(self.EsikDegeri, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 3, 1, 1)
        self.Aktar = QtWidgets.QPushButton(self.groupBox_2)
        self.Aktar.setMinimumSize(QtCore.QSize(150, 50))
        self.Aktar.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Aktar.setFont(font)
        self.Aktar.setObjectName("Aktar")
        self.gridLayout.addWidget(self.Aktar, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(220, 30))
        self.label_2.setMaximumSize(QtCore.QSize(220, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manhattan Plot"))
        self.manPlot.setText(_translate("MainWindow", "MANHATTAN PLOT"))
        self.label.setText(_translate("MainWindow", "Eşik Değerini Giriniz:"))
        self.Aktar.setText(_translate("MainWindow", "Dosya Seç"))
        self.label_2.setText(_translate("MainWindow", "Developed by Zeynep Demirtaş"))

